packages:
  iso:
    - amd-ucode
    - ansible
    - bat
    - fish
    - git
    - htop
    - less
    - networkmanager
    - openssh
    - python
    - qutebrowser
    - ripgrep
    - wget
    - xsel
  install:
    - archiso
    - autofirma
    - bacon
    - bitwarden
    - ca-certificates-dnie
    - eza
    - firefox
    - fisher
    - fzf
    - gamemode
    - jdk-openjdk
    - jdk21-openjdk
    - jinja2-cli
    - jq
    - just
    - kitty
    - lazygit
    - nvim
    - qbittorrent
    - pre-commit
    - pyenv
    - rust-analyzer
    - rustup
    - tmux
    - ttf-fira-code
    - unzip
    - vim
    - vlc
    - yq
    - zip
