custom_commands:
  - "cd /home/sotoestevez; git clone https://github.com/kriogenia/dotfiles.git"
  - "chown -R sotoestevez:sotoestevez /home/sotoestevez/dotfiles"
  - "chmod +x /home/sotoestevez/dotfiles/install.sh"
  - "cd /home/sotoestevez/dotfiles; ./install.sh"
packages:
  iso:
  - amd-ucode
  - bat
  - fish
  - git
  - less
  - networkmanager
  - python
  - ripgrep
  - xsel
  install:
  - archiso
  - eza
  - firefox
  - fisher
  - fzf
  - jq
  - just
  - kitty
  - lazygit
  - markdownlint-cli2
  - pyenv
  - rust-analyzer
  - rustup
  - tmux
  - ttf-fira-code
  - unzip
  - yq
  - zip
