packages:
- amd-ucode
- archiso
- bat
- eza
- firefox
- fish
- fisher
- fzf
- git
- jq
- just
- kitty
- lazygit
- less
- markdownlint-cli2
- networkmanager
- pyenv
- python
- ripgrep
- tmux
- ttf-fira-code
- unzip
- xsel
- yq
- zip
# separate liveusb and installation packages
