packages:
  iso:
    - amd-ucode
    - ansible
    - bat
    - fish
    - git
    - htop
    - less
    - networkmanager
    - openssh
    - python
    - qutebrowser
    - ripgrep
    - wget
    - xsel
    - yadm
  install:
    - archiso # and its test dependencies
    - edk2-conf
    - qemu-desktop

    # - autofirma
    - bacon
    - bitwarden
    # - ca-certificates-dnie
    # - ca-certificates-fnmt
    - eza
    - firefox
    - fisher
    - fzf
    - gamemode
    - jdk-openjdk
    - jdk21-openjdk
    # - jinja2-cli
    - jq
    - just
    - kitty
    - lazygit
    - nvim
    - qbittorrent
    - pre-commit
    - rust-analyzer
    - rustup
    - steam
    - tmux
    - ttf-fira-code
    - ttf-liberation
    - unzip
    - vim
    - vlc
    - yq
    # - zen-browser-bin
    - zip
