packages:
  iso:
  - amd-ucode
  - bat
  - fish
  - git
  - less
  - networkmanager
  - openssh
  - python
  - ripgrep
  - xsel
  install:
  - archiso
  - eza
  - firefox
  - fisher
  - fzf
  - jq
  - just
  - kitty
  - lazygit
  - markdownlint-cli2
  - pyenv
  - rust-analyzer
  - rustup
  - tmux
  - ttf-fira-code
  - unzip
  - yq
  - zip
