packages:
  iso:
    - amd-ucode
    - ansible
    - bat
    - fish
    - git
    - htop
    - less
    - networkmanager
    - openssh
    - python
    - qutebrowser
    - ripgrep
    - wget
    - xsel
    - yadm
  install:
    - archiso # and its test dependencies
    - edk2-ovmf
    - qemu-desktop
    - bacon
    - bitwarden
    - eza
    - firefox
    - fisher
    - fzf
    - gamemode
    - jdk-openjdk
    - jdk21-openjdk
    - jq
    - just
    - kitty
    - lazygit
    - man-db
    - nvim
    - qbittorrent
    - pre-commit
    - rust-analyzer
    - rustup
    - sddm
    - steam
    - tmux
    - ttf-fira-code
    - ttf-liberation
    - unzip
    - vim
    - vlc
    - yq
    - zip
